version: '3.1'

services:
  
  postgres:
    build:
      context: .
      dockerfile: ./Dockerfile-postgres
    image: my-postgres-container:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:4532
    container_name: my-postgres-container
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  pgadmin:
    image: elestio/pgadmin:latest
    ports:
      - 5050:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123

volumes:
  postgres-data: